/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.commonwealthrobotics;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main  extends Application {

	@Override
	public void start(Stage stage) throws Exception {
		CadoodleUpdater.stage=stage;
		Parent root = FXMLLoader.load(Main.class.getResource("ui.fxml"));

		Scene scene = new Scene(root, 620, 658);

		
		stage.setScene(scene);
		stage.show();
	}
	public static void main(String [] args) {
		CadoodleUpdater.argsFromSystem=args;
		CadoodleUpdater.project="CommonWealthRobotics";
		CadoodleUpdater.repoName=		"CaDoodle-Application";
		CadoodleUpdater.jarName=		"CaDoodle-Application.jar";
		
		launch(args);
	}

}

   
	
