name: Publish package to GitHub Packages
on:
  push:

env:
  JVM_JSON_URL: https://github.com/CommonWealthRobotics/CaDoodle-Application/releases/latest/download/jvm.json
  APP_INSTALL_URL: https://github.com/CommonWealthRobotics/CaDoodle-Application/releases/latest/download/CaDoodle-ApplicationInstall.zip

jobs:
  debian-bookworm:
    runs-on: ubuntu-24.04-arm
    container:
      image: debian:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y fakeroot binutils wget file jq curl unzip
          echo '#!/bin/sh' > /usr/local/bin/sudo
          echo 'exec "$@"' >> /usr/local/bin/sudo
          chmod +x /usr/local/bin/sudo

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Get the version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Download jvm.json and CaDoodle-ApplicationInstall.zip
        run: |
          curl -L "${{ env.JVM_JSON_URL }}" -o jvm.json
          curl -L "${{ env.APP_INSTALL_URL }}" -o CaDoodle-ApplicationInstall.zip

      - name: Download JVM (Linux-aarch64)
        run: |
          JVM_NAME=$(jq -r '.["Linux-aarch64"].name' jvm.json)
          JVM_URL=$(jq -r '.["Linux-aarch64"].url' jvm.json)
          JVM_TYPE=$(jq -r '.["Linux-aarch64"].type' jvm.json)
          echo "Downloading $JVM_URL$JVM_NAME.$JVM_TYPE"
          curl -L "$JVM_URL$JVM_NAME.$JVM_TYPE" -o "$JVM_NAME.$JVM_TYPE"
          tar -xzf "$JVM_NAME.$JVM_TYPE"
          echo "JAVA_HOME=$(pwd)/$JVM_NAME" >> $GITHUB_ENV
          echo "$(pwd)/$JVM_NAME/bin" >> $GITHUB_PATH

      - name: Build
        env:
          VERSION_SEMVER: ${{ steps.get_version.outputs.VERSION }}
        run: bash package-linux_arm64.sh

      - name: Upload math result for job Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-bookworm-lib
          path: release/*

  linux-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Download jvm.json and CaDoodle-ApplicationInstall.zip
        run: |
          curl -L "${{ env.JVM_JSON_URL }}" -o jvm.json
          curl -L "${{ env.APP_INSTALL_URL }}" -o CaDoodle-ApplicationInstall.zip

      - name: Download JVM (Linux-aarch64)
        run: |
          JVM_NAME=$(jq -r '.["Linux-aarch64"].name' jvm.json)
          JVM_URL=$(jq -r '.["Linux-aarch64"].url' jvm.json)
          JVM_TYPE=$(jq -r '.["Linux-aarch64"].type' jvm.json)
          echo "Downloading $JVM_URL$JVM_NAME.$JVM_TYPE"
          curl -L "$JVM_URL$JVM_NAME.$JVM_TYPE" -o "$JVM_NAME.$JVM_TYPE"
          tar -xzf "$JVM_NAME.$JVM_TYPE"
          echo "JAVA_HOME=$(pwd)/$JVM_NAME" >> $GITHUB_ENV
          echo "$(pwd)/$JVM_NAME/bin" >> $GITHUB_PATH

      - name: Build
        env:
          VERSION_SEMVER: ${{ steps.get_version.outputs.VERSION }}
        run: bash package-linux_arm64.sh

      - name: Upload result for job Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-lib
          path: release/*

  linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Download jvm.json and CaDoodle-ApplicationInstall.zip
        run: |
          curl -L "${{ env.JVM_JSON_URL }}" -o jvm.json
          curl -L "${{ env.APP_INSTALL_URL }}" -o CaDoodle-ApplicationInstall.zip

      - name: Download JVM (Linux-x64)
        run: |
          JVM_NAME=$(jq -r '.["Linux-x64"].name' jvm.json)
          JVM_URL=$(jq -r '.["Linux-x64"].url' jvm.json)
          JVM_TYPE=$(jq -r '.["Linux-x64"].type' jvm.json)
          echo "Downloading $JVM_URL$JVM_NAME.$JVM_TYPE"
          curl -L "$JVM_URL$JVM_NAME.$JVM_TYPE" -o "$JVM_NAME.$JVM_TYPE"
          tar -xzf "$JVM_NAME.$JVM_TYPE"
          echo "JAVA_HOME=$(pwd)/$JVM_NAME" >> $GITHUB_ENV
          echo "$(pwd)/$JVM_NAME/bin" >> $GITHUB_PATH

      - name: Build
        env:
          VERSION_SEMVER: ${{ steps.get_version.outputs.VERSION }}
        run: bash package-linux_x64.sh

      - name: Upload result for job Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux-lib
          path: release/*

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1
      - uses: microsoft/setup-msbuild@v1.1

      - name: Get the version
        id: get_version
        shell: bash
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=0.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Download jvm.json and CaDoodle-ApplicationInstall.zip
        shell: bash
        run: |
          curl -L "${{ env.JVM_JSON_URL }}" -o jvm.json
          curl -L "${{ env.APP_INSTALL_URL }}" -o CaDoodle-ApplicationInstall.zip

      - name: Download JVM (Windows-x64)
        shell: bash
        run: |
          JVM_NAME=$(jq -r '.["Windows-x64"].name' jvm.json)
          JVM_URL=$(jq -r '.["Windows-x64"].url' jvm.json)
          JVM_TYPE=$(jq -r '.["Windows-x64"].type' jvm.json)
          echo "Downloading $JVM_URL$JVM_NAME.$JVM_TYPE"
          curl -L "$JVM_URL$JVM_NAME.$JVM_TYPE" -o "$JVM_NAME.$JVM_TYPE"
          unzip -q "$JVM_NAME.$JVM_TYPE"
          echo "JAVA_HOME=$(pwd)/$JVM_NAME" >> $GITHUB_ENV
          echo "$(pwd)/$JVM_NAME/bin" >> $GITHUB_PATH
      - name: Patch publisher into manifest
        shell: bash
          run: sed -i "s/WINDOWS_PUB_UUID/${{ secrets.WINDOWS_PUB_UUID }}/" AppxManifest.xml
      - name: Build
        env:
          VERSION_SEMVER: ${{ steps.get_version.outputs.VERSION }}
        shell: bash
        run: bash package-windows_x86_64.sh

      - name: Upload result for job Windows
        uses: actions/upload-artifact@v4
        with:
          name: win-lib
          path: release/*

  macos-arm:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=1.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Download jvm.json and CaDoodle-ApplicationInstall.zip
        run: |
          curl -L "${{ env.JVM_JSON_URL }}" -o jvm.json
          curl -L "${{ env.APP_INSTALL_URL }}" -o CaDoodle-ApplicationInstall.zip

      - name: Download JVM (Mac-aarch64)
        run: |
          JVM_NAME=$(jq -r '.["Mac-aarch64"].name' jvm.json)
          JVM_URL=$(jq -r '.["Mac-aarch64"].url' jvm.json)
          JVM_TYPE=$(jq -r '.["Mac-aarch64"].type' jvm.json)
          echo "Downloading $JVM_URL$JVM_NAME.$JVM_TYPE"
          curl -L "$JVM_URL$JVM_NAME.$JVM_TYPE" -o "$JVM_NAME.$JVM_TYPE"
          unzip -q "$JVM_NAME.$JVM_TYPE"
          echo "JAVA_HOME=$(pwd)/$JVM_NAME" >> $GITHUB_ENV
          echo "$(pwd)/$JVM_NAME/bin" >> $GITHUB_PATH

      - name: Build
        env:
          VERSION_SEMVER: ${{ steps.get_version.outputs.VERSION }}
        run: bash package-macos.sh

      - name: Upload result for job Mac-arm
        uses: actions/upload-artifact@v4
        with:
          name: mac-lib-arm
          path: release/*

  macos:
    runs-on: macos-15-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=1.0.0" >> $GITHUB_OUTPUT
          fi

      - name: Download jvm.json and CaDoodle-ApplicationInstall.zip
        run: |
          curl -L "${{ env.JVM_JSON_URL }}" -o jvm.json
          curl -L "${{ env.APP_INSTALL_URL }}" -o CaDoodle-ApplicationInstall.zip

      - name: Download JVM (Mac-x64)
        run: |
          JVM_NAME=$(jq -r '.["Mac-x64"].name' jvm.json)
          JVM_URL=$(jq -r '.["Mac-x64"].url' jvm.json)
          JVM_TYPE=$(jq -r '.["Mac-x64"].type' jvm.json)
          echo "Downloading $JVM_URL$JVM_NAME.$JVM_TYPE"
          curl -L "$JVM_URL$JVM_NAME.$JVM_TYPE" -o "$JVM_NAME.$JVM_TYPE"
          unzip -q "$JVM_NAME.$JVM_TYPE"
          echo "JAVA_HOME=$(pwd)/$JVM_NAME" >> $GITHUB_ENV
          echo "$(pwd)/$JVM_NAME/bin" >> $GITHUB_PATH

      - name: Build
        env:
          VERSION_SEMVER: ${{ steps.get_version.outputs.VERSION }}
        run: bash package-macos.sh

      - name: Upload result for job Mac-x86
        uses: actions/upload-artifact@v4
        with:
          name: mac-lib-x86
          path: release/*

  publish:
    runs-on: ubuntu-latest
    needs: [macos, windows, linux, macos-arm, linux-arm, debian-bookworm]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Get tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Check output
        env:
          VERSION_SEMVER: ${{ steps.vars.outputs.tag }}
        run: |
          echo $VERSION_SEMVER
          echo ${{ steps.vars.outputs.tag }}

      - name: Download result for job Bookworm
        uses: actions/download-artifact@v4
        with:
          name: linux-arm-bookworm-lib
          path: .

      - name: Rename files for Bookworm
        env:
          VERSION_SEMVER: ${{ steps.vars.outputs.tag }}
        run: |
          mv CaDoodle-Linux-arm64.AppImage CaDoodle-Linux-arm64-bookworm.AppImage
          mv CaDoodle-Linux-arm64.deb CaDoodle-Linux-arm64-bookworm.deb

      - name: Download result for job Windows
        uses: actions/download-artifact@v4
        with:
          name: win-lib
          path: .

      - name: Download result for job Linux
        uses: actions/download-artifact@v4
        with:
          name: linux-lib
          path: .

      - name: Download result for job Mac-arm
        uses: actions/download-artifact@v4
        with:
          name: mac-lib-arm
          path: .

      - name: Download result for job Mac-x86
        uses: actions/download-artifact@v4
        with:
          name: mac-lib-x86
          path: .

      - name: Download result for job Linux ARM
        uses: actions/download-artifact@v4
        with:
          name: linux-arm-lib
          path: .

      - name: Check downloads
        run: |
          echo "Downloads:"
          ls -als

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CaDoodle-Linux-arm64.AppImage
            CaDoodle-Linux-arm64.deb
            CaDoodle-Linux-x86_64.AppImage
            CaDoodle-Linux-x86_64.deb
            CaDoodle-Windows-System-x86_64.exe
            CaDoodle-Windows-x86_64.exe
            CaDoodle-Windows-x86_64.zip
            CaDoodle-MacOS-x86_64.dmg
            CaDoodle-MacOS-arm64.dmg
            CaDoodle-Linux-arm64-bookworm.AppImage
            CaDoodle-Linux-arm64-bookworm.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}